In [ ]:
##1





import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
##2




import numpy as np
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
##3





import numpy as np
arr = np.arange(10, 50)
reversed_arr = arr[::-1]
print(reversed_arr)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [4]:
##4





import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
##5






import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices[0]) 


[0 1 4]


In [6]:
##6







import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
##7







import numpy as np

random_matrix = np.random.rand(3, 3)
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Random 3x3 Matrix:")
print(random_matrix)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random 3x3 Matrix:
[[0.44706353 0.89178934 0.11578427]
 [0.64755427 0.99482359 0.14426462]
 [0.99672091 0.33373749 0.04939463]]

Minimum Value: 0.04939462955058882
Maximum Value: 0.9967209116062262


In [8]:
##8







import numpy as np

random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print("Original 5x5 Random Matrix:")
print(random_matrix)
print("\nNormalized 5x5 Matrix:")
print(normalized_matrix)


Original 5x5 Random Matrix:
[[0.51787992 0.16940094 0.80360668 0.74937881 0.22984072]
 [0.08057182 0.21826047 0.95103772 0.06383071 0.18830554]
 [0.05163238 0.13145714 0.36703029 0.61626709 0.64897332]
 [0.81299794 0.82643411 0.10735095 0.22790178 0.32784284]
 [0.44671137 0.0672271  0.13666138 0.55667272 0.51455595]]

Normalized 5x5 Matrix:
[[0.51839535 0.13094048 0.83607943 0.7757864  0.19814019]
 [0.0321762  0.18526474 1.         0.01356266 0.15195947]
 [0.         0.08875282 0.35067383 0.6277867  0.66415098]
 [0.84652106 0.86146001 0.06195045 0.19598438 0.30710343]
 [0.43926689 0.01733893 0.09453914 0.56152695 0.5146996 ]]


In [9]:
##9







import numpy as np

array = np.array([1, 3, 5, 11, 15, 20, 25])
target = 14
closest_value = array[np.abs(array - target).argmin()]
print("Closest value to", target, "is", closest_value)


Closest value to 14 is 15


In [10]:
##10







import numpy as np

array = np.array([[5, 9, 3], [10, 2, 15], [6, 7, 8]])

for i in range(array.shape[0]):
    max_index = array[i].argmax() 
    array[i, max_index] = 0       
print("Updated array:")
print(array)


Updated array:
[[ 5  0  3]
 [10  2  0]
 [ 6  7  0]]


In [11]:
##11






import numpy as np
from collections import Counter

array = np.array([2, 3, 2, 5, 8, 3, 3, 7, 2, 3, 5, 5, 5, 5])
most_common_value = Counter(array).most_common(1)[0][0]
print("Most common value:", most_common_value)


Most common value: 5


In [12]:
##12







import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transpose = array.T
matrix_product = np.dot(array, transpose)
print("Matrix product of the array and its transpose:")
print(matrix_product)


Matrix product of the array and its transpose:
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [13]:
##13







import numpy as np

matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", determinant)


Determinant of the matrix: -306.0


In [14]:
##14







import numpy as np

matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

determinant = np.linalg.det(matrix)
if determinant == 0:
    print("The matrix is not invertible (determinant is zero).")
else:
    inverse = np.linalg.inv(matrix)
    print("Inverse of the matrix:")
    print(inverse)


Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
